<?php

namespace ContainerIpxPOpT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T4Xo3pfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T4Xo3pf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T4Xo3pf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\PrestaRepository', 'getPrestaRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\PrestaRepository',
        ]);
    }
}
