<?php

namespace ContainerE5C8R2l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JQYI_OPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JQYI.OP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JQYI.OP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['privates', '.errored.O_PC_f2', NULL, 'Cannot determine controller argument for "App\\Controller\\PrestationController::create()": the $manager argument is type-hinted with the non-existent class or interface: "Doctrine\\Common\\Persistence\\ObjectManager".'],
        ], [
            'manager' => '?',
        ]);
    }
}
