<?php

namespace ContainerE5C8R2l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8Wb436QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Wb436Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8Wb436Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PrestationController::create' => ['privates', '.service_locator.JQYI.OP', 'get_ServiceLocator_JQYI_OPService', true],
            'App\\Controller\\PrestationController::index' => ['privates', '.service_locator.T4Xo3pf', 'get_ServiceLocator_T4Xo3pfService', true],
            'App\\Controller\\PrestationController::show' => ['privates', '.service_locator.sNMRf4_', 'get_ServiceLocator_SNMRf4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\PrestationController:create' => ['privates', '.service_locator.JQYI.OP', 'get_ServiceLocator_JQYI_OPService', true],
            'App\\Controller\\PrestationController:index' => ['privates', '.service_locator.T4Xo3pf', 'get_ServiceLocator_T4Xo3pfService', true],
            'App\\Controller\\PrestationController:show' => ['privates', '.service_locator.sNMRf4_', 'get_ServiceLocator_SNMRf4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\PrestationController::create' => '?',
            'App\\Controller\\PrestationController::index' => '?',
            'App\\Controller\\PrestationController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PrestationController:create' => '?',
            'App\\Controller\\PrestationController:index' => '?',
            'App\\Controller\\PrestationController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
