<?php

namespace ContainerE5C8R2l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_OPCF2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.O_PC_f2' shared service.
     *
     * @return \Doctrine\Common\Persistence\ObjectManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\PrestationController::create()": the $manager argument is type-hinted with the non-existent class or interface: "Doctrine\\Common\\Persistence\\ObjectManager".');
    }
}
