<?php

namespace ContainerAdlwUrJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EiYULdoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eiYULdo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eiYULdo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'prestationRepository' => ['privates', 'App\\Repository\\PrestationRepository', 'getPrestationRepositoryService', true],
        ], [
            'prestationRepository' => 'App\\Repository\\PrestationRepository',
        ]);
    }
}
