<?php

namespace ContainerYzkX23D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VI5bDTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v_I5bDT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v_I5bDT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.eiYULdo', 'get_ServiceLocator_EiYULdoService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\PrestationController::form' => ['privates', '.service_locator.Pn8ZKjs', 'get_ServiceLocator_Pn8ZKjsService', true],
            'App\\Controller\\PrestationController::index' => ['privates', '.service_locator.d2d5XWd', 'get_ServiceLocator_D2d5XWdService', true],
            'App\\Controller\\PrestationController::show' => ['privates', '.service_locator.i3NsxiZ', 'get_ServiceLocator_I3NsxiZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.eiYULdo', 'get_ServiceLocator_EiYULdoService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\PrestationController:form' => ['privates', '.service_locator.Pn8ZKjs', 'get_ServiceLocator_Pn8ZKjsService', true],
            'App\\Controller\\PrestationController:index' => ['privates', '.service_locator.d2d5XWd', 'get_ServiceLocator_D2d5XWdService', true],
            'App\\Controller\\PrestationController:show' => ['privates', '.service_locator.i3NsxiZ', 'get_ServiceLocator_I3NsxiZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\PrestationController::form' => '?',
            'App\\Controller\\PrestationController::index' => '?',
            'App\\Controller\\PrestationController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\PrestationController:form' => '?',
            'App\\Controller\\PrestationController:index' => '?',
            'App\\Controller\\PrestationController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
