<?php

namespace ContainerPEmqD99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P_Uj4AeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p.Uj4Ae' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p.Uj4Ae'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', '.errored.7xV50Qf', NULL, 'Cannot determine controller argument for "App\\Controller\\PrestationController::index()": the $repo argument is type-hinted with the non-existent class or interface: "App\\Repository\\PrestaRepository".'],
        ], [
            'repo' => '?',
        ]);
    }
}
