<?php

namespace ContainerUP6BVfu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D2d5XWdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d2d5XWd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d2d5XWd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\PrestationRepository', 'getPrestationRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\PrestationRepository',
        ]);
    }
}
