<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerAxMVh6B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxMVh6B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAxMVh6B.legacy');
=======
if (\class_exists(\ContainerUP6BVfu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUP6BVfu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUP6BVfu.legacy');
>>>>>>> origin/feature-PagePrestation

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerAxMVh6B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAxMVh6B\App_KernelDevDebugContainer([
    'container.build_hash' => 'AxMVh6B',
    'container.build_id' => '7adbbf5a',
    'container.build_time' => 1633698107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxMVh6B');
=======
    \class_alias(\ContainerUP6BVfu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUP6BVfu\App_KernelDevDebugContainer([
    'container.build_hash' => 'UP6BVfu',
    'container.build_id' => 'c91ebb63',
    'container.build_time' => 1633955203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUP6BVfu');
>>>>>>> origin/feature-PagePrestation
