<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5vTIVua\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5vTIVua/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5vTIVua.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5vTIVua\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5vTIVua\App_KernelDevDebugContainer([
    'container.build_hash' => '5vTIVua',
    'container.build_id' => 'd086fda1',
    'container.build_time' => 1633702879,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5vTIVua');
