<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTJzT3vs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTJzT3vs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTJzT3vs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTJzT3vs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTJzT3vs\App_KernelDevDebugContainer([
    'container.build_hash' => 'TJzT3vs',
    'container.build_id' => '0f5266f4',
    'container.build_time' => 1633092654,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTJzT3vs');
